In [56]:
import torch
import numpy as np
import cv2
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scipy.spatial import cKDTree

print(torch.cuda.is_available())

True


In [21]:
class Engine(object):
    def __init__(self, state={}):
        self.state = state
        self.state['use_gpu'] = True
        
    def print_fun(self, st1):
        self.st1 = st1
        print(self.state)
        self.state['ok'] = False
        print(self.state)
    
    def print_fun2(self):
        print(self.st1)
        

In [22]:
state = {'a':3}
engine = Engine(state)
engine.print_fun('guapi')
engine.print_fun2()



{'a': 3, 'use_gpu': True}
{'a': 3, 'use_gpu': True, 'ok': False}
guapi


In [27]:
mapping = {")": "(", "}": "{", "]": "["}
if ')' in mapping:
    print('yes')
else:
    print('no')

mapping[')']


yes


'('

In [6]:
a = np.array([2,3,4])
b = torch.from_numpy(a)
b




tensor([2, 3, 4], dtype=torch.int32)

In [16]:
img = cv2.imread('IDRiD_010.jpg')
surf = cv2.xfeatures2d.SURF_create(1000)
sift = cv2.xfeatures2d.SIFT_create(1000)

kp, des = surf.detectAndCompute(img, None)
des = des[:20]

print(des[0])
des.shape

minmax_normalizer = MinMaxScaler()
feature_vector = minmax_normalizer.fit_transform(des)
feature_vector

[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  2.3355761e-03  1.4735240e-03  2.4871361e-03  1.6537141e-03
  9.4107585e-03  2.0169979e-02  9.4107585e-03  2.0465791e-02
  9.5559657e-03  1.0951672e-02  9.5559657e-03  1.0960944e-02
  7.1244844e-04  8.4944977e-04  7.1244844e-04  1.5918666e-03
  1.4351934e-02  5.2778567e-03  1.7055325e-02  1.0892163e-02
  4.8058376e-01  4.0083449e-02  4.8058376e-01  2.5708407e-01
  4.9504796e-03  4.2158393e-03  4.9504796e-03  4.3744976e-03
  3.6112848e-03  4.4850298e-04  3.6112848e-03  1.2978252e-03
  2.3645969e-01  2.3324345e-01  2.3877415e-01  2.7076527e-01
  2.2194313e-01  1.9695631e-01  2.2397760e-01  2.8309110e-01
  3.3249676e-03 -1.6321965e-03  4.4885608e-03  6.9328225e-03
  4.0107808e-04  3.7261829e-04  4.3510742e-04  3.7261829e-04
  6.4810365e-02 -1.0786165e-02  6.4810365e-02  1.8588895e-02
  4.4543594e-03  9.5419483e-03  4.7923112e-03  9.5419483e-03
  1.2207802e-03  1.2254722e-03  1.3149027e-03  1.2357859e-03]


array([[0.33941707, 0.58696413, 0.        , ..., 1.        , 0.6826894 ,
        0.68227327],
       [1.        , 0.35746104, 0.6264274 , ..., 0.24314597, 1.        ,
        0.49539223],
       [0.62784845, 0.27266404, 0.27234694, ..., 0.29688364, 0.7386581 ,
        0.        ],
       ...,
       [0.3505692 , 0.5640164 , 0.0378473 , ..., 0.5942051 , 0.19634831,
        0.36340365],
       [0.8828753 , 0.76704276, 0.5111529 , ..., 0.3273621 , 0.25801915,
        0.07616112],
       [0.33941707, 0.58696413, 0.        , ..., 0.37822244, 0.6286168 ,
        0.1531798 ]], dtype=float32)

In [58]:
matrix = np.array([[1, 1],
               [2, 2],
               [5, 5],
               [6, 6]]
              )

search_vec = np.array([3, 3])
matrix_tensor = torch.from_numpy(matrix)
print(matrix_tensor)
search_ten = torch.from_numpy(search_vec)



tensor([[1, 1],
        [2, 2],
        [5, 5],
        [6, 6]], dtype=torch.int32)


In [71]:
a1 = np.empty(shape=(2,1,4,5))
b1 = torch.from_numpy(a1)
print(b1.shape)
print(torch.squeeze(b1).shape)

torch.Size([2, 1, 4, 5])
torch.Size([2, 4, 5])


In [72]:
alist = [2,3,4,54,23,34,1,0,9,34]
for i in range(len(alist)-1, 0, -1):
    print(i)



9
8
7
6
5
4
3
2
1


In [73]:
a= 9
b=28
b,a = a,b
print(a,b)



28 9
